spring.application.name=journal

# 1. ??????????? ?? ???? ?????
spring.datasource.url=jdbc:postgresql://ep-quiet-river-al71k91c.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DRiKtH53nyxg

# 2. ???????????? SPRING DATA JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true